package http.handlers.util;

public enum Endpoint {
    GET_TASKS, GET_TASK_BY_ID, POST_TASK, DELETE_TASK,
    GET_SUBTASKS, GET_SUBTASK_BY_ID, POST_SUBTASK, DELETE_SUBTASK,
    GET_EPICS, GET_EPIC_BY_ID, POST_EPIC, GET_EPIC_SUBTASKS, DELETE_EPIC,
    GET_HISTORY, GET_PRIORITIZED, UNKNOWN
}

